defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  # awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  special_key: '12345678'

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults